version: 1.0.0_b{build}-{branch}

os: Visual Studio 2017

environment:
  TERM: dumb
  PYTHON_BIN: python
  CRAM_SHELL: "C:\\msys64\\usr\\bin\\sh.exe"
  matrix:
  - COMPILER: msvc
    BXF_PLATFORM: x86
    GENERATOR: "Visual Studio 15 2017"
    CFLAGS: /MP
    CXXFLAGS: /MPx
    BUILD_FLAGS: /verbosity:m
  - COMPILER: msvc
    BXF_PLATFORM: x64
    GENERATOR: "Visual Studio 15 2017"
    CFLAGS: /MP
    CXXFLAGS: /MP
    BUILD_FLAGS: /verbosity:m
  - COMPILER: msvc
    BXF_PLATFORM: ARM
    GENERATOR: "Visual Studio 15 2017"
    CFLAGS: /MP
    CXXFLAGS: /MP
    BUILD_FLAGS: /verbosity:m
  - COMPILER: msvc
    BXF_PLATFORM: ARM64
    GENERATOR: "Visual Studio 15 2017"
    CFLAGS: /MP
    CXXFLAGS: /MP
    BUILD_FLAGS: /verbosity:m
  - COMPILER: mingw
    BXF_PLATFORM: x86
    GENERATOR: "MSYS Makefiles"
    CMAKE_OPTS: -DCMAKE_SYSTEM_PROCESSOR=x86 -DCMAKE_TOOLCHAIN_FILE=../.cmake/Toolchains/Toolchain-mingw-w64.cmake
    BUILD_FLAGS: VERBOSE=1
  - COMPILER: mingw
    BXF_PLATFORM: x64
    GENERATOR: "MSYS Makefiles"
    CMAKE_OPTS: -DCMAKE_SYSTEM_PROCESSOR=x64 -DCMAKE_TOOLCHAIN_FILE=../.cmake/Toolchains/Toolchain-mingw-w64.cmake
    BUILD_FLAGS: -j2

configuration:
  - Debug
  - RelWithDebInfo

init:
  # Disable windows process crash popup
  # See: https://msdn.microsoft.com/en-us/library/bb513638%28VS.85%29.aspx
  - reg add "HKLM\SYSTEM\CurrentControlSet\Control\Windows" /f /v ErrorMode /t REG_DWORD /d 2
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /t REG_DWORD /d 1
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v Disable /t REG_DWORD /d 1

  - set PATH=C:\Python35;C:\Python35\Scripts;C:\msys64\mingw32\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%APPVEYOR_BUILD_FOLDER%\build;%APPVEYOR_BUILD_FOLDER%\build\Debug;%PATH%
  - set MSYSTEM=MINGW64
  - pip install cram==0.7

  # Remove Xamarin msbuild warnings
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

install:
  - ps: $env:RELEASE_NAME = $env:APPVEYOR_REPO_BRANCH -replace "/", "-"
  # Hack to make git think it is on the tip of the repo branch
  - 'git checkout -B %APPVEYOR_REPO_BRANCH%'

  # Patch buggy cram
  - sh -c "patch /c/Python35/lib/site-packages/cram/_test.py .cmake/cram-env.patch"

  - mkdir build && cd build
  - >
      cmake
      -Wno-dev
      -DCMAKE_INSTALL_PREFIX=boxfort-%RELEASE_NAME%
      %CMAKE_OPTS%
      --config "%CONFIGURATION%"
      -A %BXF_PLATFORM%
      -G "%GENERATOR%"
      ..

build_script:
  - cmake --build . -- %BUILD_FLAGS%

test_script:
  - ctest -j2 --output-on-failure --timeout=10
